blank_issues_enabled: false
contact_links:
  - name: Discord
    url: https://discord.gg/WVFNWEvuqX
    about: Report an issue on our official Discord!
  - name: Email
    url: mailto:gamercoder215@teaminceptus.us
    about: Email GamerCoder215 if needed.
